import { useEffect, useRef } from "react";
import { useStore } from "../state/store";
import { CloseIcon } from "./icons";

export function AboutDialog() {
  const data = useStore((s) => s.data);
  const setAboutOpen = useStore((s) => s.setAboutOpen);
  const ref = useRef<HTMLDialogElement>(null);

  useEffect(() => {
    const d = ref.current!;
    d.showModal();
    const onClose = () => setAboutOpen(false);
    d.addEventListener("close", onClose);
    return () => d.removeEventListener("close", onClose);
  }, [setAboutOpen]);

  const sources = data ? Object.values(data.catalog.sources).filter((s) => !s.id.startsWith("ads-")) : [];
  const papers = data ? Object.values(data.catalog.sources).filter((s) => s.id.startsWith("ads-")) : [];

  return (
    <dialog ref={ref} className="about" aria-labelledby="about-h" onClick={(e) => e.target === ref.current && ref.current?.close()}>
      <div className="about-inner">
        <header>
          <h1 id="about-h">About GalaxyMaps</h1>
          <button type="button" className="icon-btn" aria-label="Close" onClick={() => ref.current?.close()}>
            <CloseIcon />
          </button>
        </header>
        <p>GalaxyMaps puts real catalog positions on a familiar map so you can search, explore and get “directions” across the universe.</p>

        <h2>How the numbers work</h2>
        <ul>
          <li>All positions are 3D vectors in the ICRF frame centered on the Sun, in kilometres. Distances are full 3D separations; the flat map is only a projection.</li>
          <li>Between two planets, directions use an idealized Hohmann transfer (circular, coplanar orbits; the Sun's gravity only), departing at the next real alignment. Everywhere else they use a straight line at constant speed. A separate benchmark always shows the direct distance at light speed or at Voyager 1's measured speed. None of these is a mission plan.</li>
          <li>Planets, moons and spacecraft come from JPL Horizons for the date shown at the bottom of the map.</li>
          <li>Star distances come from parallaxes only when the parallax error is at most 20%; otherwise we use published literature distances or mark routing unavailable.</li>
          <li>Galaxy distances are static (redshift-independent where available). We don't draw routes across cosmological distances, where expansion makes a straight-line trip meaningless.</li>
          <li>The observable-universe view is schematic: directions are true, distances are compressed logarithmically, and the edge is the comoving particle horizon (≈ 46 billion light-years, Planck 2018).</li>
          <li>Symbols are enlarged so you can see them. Their size never affects distances.</li>
        </ul>

        <h2>Imagery labels</h2>
        <ul>
          <li><strong>Observed image</strong>: a real telescope or spacecraft image.</li>
          <li><strong>Scientific illustration</strong>: an artist's or scientist's rendering.</li>
          <li><strong>Texture map</strong>: a global map built from spacecraft data, wrapped on a sphere.</li>
          <li><strong>AI reconstruction</strong>: generated by Grok Imagine from catalog data. Artistic, not an observation.</li>
        </ul>

        <h2>Keyboard</h2>
        <ul className="keys">
          <li><kbd>/</kbd> search</li>
          <li><kbd>+</kbd> <kbd>−</kbd> zoom</li>
          <li><kbd>←</kbd> <kbd>↑</kbd> <kbd>→</kbd> <kbd>↓</kbd> orbit when locked, pan otherwise</li>
          <li><kbd>H</kbd> home: Earth close-up</li>
          <li><kbd>R</kbd> reset the locked view</li>
          <li><kbd>Space</kbd> play / pause time</li>
          <li><kbd>F</kbd> fit route</li>
          <li><kbd>L</kbd> switch layer</li>
          <li><kbd>D</kbd> directions</li>
          <li><kbd>Esc</kbd> close a menu, then leave the lock, then close panels</li>
        </ul>

        <h2>Data sources</h2>
        <ul className="sources">
          {sources.map((s) => (
            <li key={s.id}>
              <a href={s.url} target="_blank" rel="noreferrer">{s.title}</a>
              {s.license && <span className="muted"> · {s.license}</span>}
              {s.note && <span className="muted"> · {s.note}</span>}
            </li>
          ))}
        </ul>
        {papers.length > 0 && (
          <details>
            <summary>{papers.length} literature distance references</summary>
            <ul className="sources">
              {papers.map((s) => (
                <li key={s.id}>
                  <a href={s.url} target="_blank" rel="noreferrer">{s.title}</a>
                </li>
              ))}
            </ul>
          </details>
        )}
        <p className="muted small">
          Catalog {data?.catalog.version} · generated {data?.catalog.generated.slice(0, 10)} · {data?.catalog.stars.count.toLocaleString()} stars within {data?.catalog.stars.maxDistancePc} pc. The Milky Way seen from outside is a reconstruction based on published spiral-arm models, not a photograph; the sky panorama is NASA/Goddard SVS Deep Star Maps 2020.
        </p>
      </div>
    </dialog>
  );
}
