import { useEffect, useState } from "react";
import { useStore } from "../state/store";
import { getEngine } from "../map/engineRef";
import type { CatalogObject, ImageryKind } from "../lib/types";
import { positionOf } from "../lib/route";
import { distance } from "../lib/vec";
import { formatDistance, formatDistanceSecondary, formatUncertainty } from "../lib/format";
import { TYPE_LABEL } from "../lib/search";
import { DirectionsIcon, PinIcon, CloseIcon, SparkleIcon, ExternalIcon, WarningIcon, CompassIcon } from "./icons";
import { ObjectIcon } from "./ObjectIcon";
import { useServerStatus } from "./useServerStatus";

export const IMAGERY_LABEL: Record<ImageryKind, string> = {
  observed: "Observed image",
  illustration: "Scientific illustration",
  texture: "Texture map",
  "ai-reconstruction": "AI reconstruction",
};

const QUALITY_LABEL = { precise: "Precise", good: "Good", approximate: "Approximate", uncertain: "Uncertain" } as const;

interface AiImage {
  image: string;
  prompt: string;
  model: string;
}

export function PlaceCard({ obj }: { obj: CatalogObject }) {
  const data = useStore((s) => s.data)!;
  const jd = useStore((s) => s.jd);
  const select = useStore((s) => s.select);
  const openDirections = useStore((s) => s.openDirections);
  const status = useServerStatus();
  const [ai, setAi] = useState<AiImage | null>(null);
  const [aiState, setAiState] = useState<"idle" | "loading" | "error">("idle");
  const [aiError, setAiError] = useState("");
  const [showAi, setShowAi] = useState(false);

  useEffect(() => {
    setAi(null);
    setAiState("idle");
    setShowAi(false);
  }, [obj.id]);

  const ctx = { eph: data.eph, jdTdb: jd };
  const p = positionOf(obj, ctx);
  const earth = data.byId.get("earth")!;
  const pe = positionOf(earth, ctx);
  const fromEarth = p && pe && obj.id !== "earth" ? distance(p, pe) : null;
  const fromSun = p && obj.id !== "sun" ? Math.hypot(...p) : null;
  const src = (id?: string) => (id ? data.catalog.sources[id] : undefined);
  const unc = obj.distance ? formatUncertainty(obj.distance.plusKm, obj.distance.minusKm) : null;
  const facts = obj.facts.filter((f) => !/^distance from (the )?(sun|earth)/i.test(f.label));

  const generate = async () => {
    setAiState("loading");
    setShowAi(true);
    try {
      const r = await fetch("/api/imagine", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ objectId: obj.id }) });
      const j = await r.json().catch(() => ({}));
      if (!r.ok) throw new Error(j.error ?? `HTTP ${r.status}`);
      setAi(j);
      setAiState("idle");
    } catch (e) {
      setAiError((e as Error).message);
      setAiState("error");
    }
  };

  const aiDisabledReason = !status ? "Checking server…" : !status.reachable ? "The SpaceMaps API server isn't running." : !status.grokConfigured ? "Grok Imagine isn't configured (no XAI_API_KEY on the server)." : null;
  const image = showAi && ai ? { src: ai.image, kind: "ai-reconstruction" as const, title: `${obj.name} (AI reconstruction)`, credit: `Generated by ${ai.model} from SpaceMaps catalog data`, license: "AI-generated", sourceUrl: "" } : obj.image;

  return (
    <article className="panel place" aria-labelledby="place-title">
      <div className={`place-hero ${image ? "" : "no-image"}`}>
        {image ? (
          <img src={image.src} alt={image.title} />
        ) : (
          <div className="hero-placeholder">
            <ObjectIcon obj={obj} size={72} />
            <span>No freely licensed image in our dataset</span>
          </div>
        )}
        {image && <span className={`imagery-badge kind-${image.kind}`}>{IMAGERY_LABEL[image.kind]}</span>}
        <button type="button" className="icon-btn hero-close" aria-label="Close place card" onClick={() => select(null)}>
          <CloseIcon size={20} />
        </button>
      </div>
      {image && (
        <p className="image-credit">
          {image.kind === "ai-reconstruction" ? (
            <>Artistic visualization, not an observation. {image.credit}.</>
          ) : (
            <>
              {image.credit} · {image.licenseUrl ? <a href={image.licenseUrl} target="_blank" rel="noreferrer">{image.license}</a> : image.license}
              {image.sourceUrl && (
                <>
                  {" · "}
                  <a href={image.sourceUrl} target="_blank" rel="noreferrer">Source</a>
                </>
              )}
            </>
          )}
        </p>
      )}

      <header className="place-head">
        <h1 id="place-title">{obj.name}</h1>
        <p className="place-sub">{obj.subtitle}</p>
        <p className="place-type">
          <span className="tag">{TYPE_LABEL[obj.type]}</span>
          {obj.hasRings && <span className="tag">Rings</span>}
          {obj.exoplanets?.count ? <span className="tag">{obj.exoplanets.count} exoplanet{obj.exoplanets.count > 1 ? "s" : ""}</span> : null}
        </p>
      </header>

      <div className="action-row">
        <button type="button" className="action primary" onClick={() => openDirections(obj.id)} disabled={!obj.route.supported} title={obj.route.supported ? "Directions" : "Routing unavailable"}>
          <span className="action-icon"><DirectionsIcon /></span>
          Directions
        </button>
        <button type="button" className="action" onClick={() => openDirections(undefined, obj.id)} disabled={!obj.route.supported}>
          <span className="action-icon"><PinIcon /></span>
          Start here
        </button>
        <button type="button" className="action" onClick={() => getEngine()?.flyToObject(obj.id)}>
          <span className="action-icon"><CompassIcon /></span>
          Zoom to
        </button>
        {obj.featured && obj.type !== "spacecraft" && (
          <button type="button" className="action" onClick={ai ? () => setShowAi((v) => !v) : generate} disabled={!!aiDisabledReason || aiState === "loading"} title={aiDisabledReason ?? "Generate an AI reconstruction with Grok Imagine"}>
            <span className="action-icon"><SparkleIcon /></span>
            {aiState === "loading" ? "Generating…" : ai ? (showAi ? "Real image" : "AI view") : "AI view"}
          </button>
        )}
      </div>
      {aiDisabledReason && obj.featured && obj.type !== "spacecraft" && <p className="hint">AI view: {aiDisabledReason}</p>}
      {aiState === "error" && <p className="hint error">AI view failed: {aiError}</p>}
      {showAi && ai && (
        <details className="ai-prompt">
          <summary>What the AI was told</summary>
          <p>{ai.prompt}</p>
        </details>
      )}

      {!obj.route.supported && (
        <div className="callout warn" role="note">
          <WarningIcon size={18} />
          <span><strong>Routing unavailable.</strong> {obj.route.reason}</span>
        </div>
      )}

      <section className="facts" aria-label="Distance">
        <dl>
          {fromEarth != null && (
            <div className="fact">
              <dt>From Earth{obj.position?.kind === "ephemeris" ? " (on map date)" : ""}</dt>
              <dd>
                {formatDistance(fromEarth)} <span className="muted">{formatDistanceSecondary(fromEarth)}</span>
              </dd>
            </div>
          )}
          {fromSun != null && (
            <div className="fact">
              <dt>From the Sun</dt>
              <dd>
                {formatDistance(fromSun)}
                {unc && obj.position?.kind !== "ephemeris" && <span className="muted"> {unc}</span>}
              </dd>
            </div>
          )}
          {obj.distance && obj.id !== "sun" && (
            <div className="fact">
              <dt>Distance quality</dt>
              <dd>
                <span className={`quality q-${obj.distance.quality}`}>{QUALITY_LABEL[obj.distance.quality]}</span>{" "}
                <span className="muted">{obj.distance.method ?? obj.distance.type}</span>
                {src(obj.distance.sourceId) && (
                  <span className="muted">
                    {" · "}
                    <a href={src(obj.distance.sourceId)!.url} target="_blank" rel="noreferrer">{src(obj.distance.sourceId)!.title}</a>
                  </span>
                )}
                {obj.distance.note && <span className="note">{obj.distance.note}</span>}
              </dd>
            </div>
          )}
        </dl>
      </section>

      {facts.length > 0 && (
        <section className="facts" aria-labelledby="facts-h">
          <h2 id="facts-h" className="section-title">Facts</h2>
          <dl>
            {facts.map((f) => (
              <div className="fact" key={f.label}>
                <dt>{f.label}</dt>
                <dd>
                  {f.value}
                  {src(f.sourceId) && (
                    <a className="src-link" href={src(f.sourceId)!.url} target="_blank" rel="noreferrer" title={src(f.sourceId)!.title} aria-label={`Source: ${src(f.sourceId)!.title}`}>
                      <ExternalIcon size={12} />
                    </a>
                  )}
                </dd>
              </div>
            ))}
          </dl>
        </section>
      )}

      {obj.exoplanets && obj.exoplanets.planets.length > 0 && (
        <section aria-labelledby="exo-h">
          <h2 id="exo-h" className="section-title">Confirmed planets</h2>
          <ul className="exo-list">
            {obj.exoplanets.planets.map((pl) => (
              <li key={pl.name}>
                <strong>{pl.name}</strong>
                <span className="muted">
                  {[pl.periodDays != null && `${pl.periodDays < 10 ? pl.periodDays.toFixed(2) : Math.round(pl.periodDays)}-day orbit`, pl.radiusEarth != null && `${pl.radiusEarth.toFixed(2)} R⊕`, pl.massEarth != null && `${pl.massEarth.toFixed(1)} M⊕`, pl.discoveryYear && `found ${pl.discoveryYear}`].filter(Boolean).join(" · ")}
                </span>
              </li>
            ))}
          </ul>
          <p className="source-line">Source: <a href={src(obj.exoplanets.sourceId)?.url} target="_blank" rel="noreferrer">{src(obj.exoplanets.sourceId)?.title}</a></p>
        </section>
      )}

      {obj.summary && (
        <section aria-labelledby="about-h">
          <h2 id="about-h" className="section-title">About</h2>
          <p className="summary">{obj.summary.text}</p>
          <p className="source-line">
            From <a href={obj.summary.url} target="_blank" rel="noreferrer">Wikipedia</a>, CC BY-SA 4.0
          </p>
        </section>
      )}

      <section aria-labelledby="src-h">
        <h2 id="src-h" className="section-title">Sources</h2>
        <ul className="source-list">
          {[...new Set(obj.sourceIds)].map((id) => src(id)).filter(Boolean).map((s) => (
            <li key={s!.id}>
              <a href={s!.url} target="_blank" rel="noreferrer">{s!.title}</a>
            </li>
          ))}
          {obj.position && <li className="muted">Position: {obj.position.method}</li>}
        </ul>
      </section>
    </article>
  );
}
