/**
 * Curated destination lists for the SpaceMaps dataset. Every numeric value used by the
 * app comes from a fetched catalog response or from a literature entry below that cites
 * its bibcode; nothing here is generated by an LLM.
 */

export const EPHEMERIS_START = "2026-09-01";
export const EPHEMERIS_STOP = "2027-03-01";
/** Reference epoch for distances quoted in cards (the BigRed//Hacks demo day). */
export const REFERENCE_EPOCH = "2026-10-04";

export interface SolarBody {
  id: string;
  name: string;
  aliases?: string[];
  type: "star" | "planet" | "dwarf-planet" | "moon" | "asteroid" | "comet" | "spacecraft";
  horizons: string;
  /** Parent ephemeris key for moons (elements are fetched relative to it). */
  parent?: string;
  factsheet?: string;
  wiki?: string;
  texture?: string;
  color: string;
  priority: number;
  /** IAU WGCCRE (Archinal et al. 2018) pole RA/Dec, J2000, used only to orient textures. */
  pole?: { ra: number; dec: number };
  rings?: { innerKm: number; outerKm: number; texture?: string };
  /** Fallback radius when neither the NASA fact sheet nor Horizons provides one. */
  subtitle: string;
}

export const SOLAR_BODIES: SolarBody[] = [
  { id: "sun", name: "Sun", aliases: ["Sol"], type: "star", horizons: "10", wiki: "Sun", texture: "2k_sun.jpg", color: "#ffb43f", priority: 100, pole: { ra: 286.13, dec: 63.87 }, subtitle: "G2V main-sequence star · Solar System" },
  { id: "mercury", name: "Mercury", type: "planet", horizons: "199", factsheet: "MERCURY", wiki: "Mercury_(planet)", texture: "2k_mercury.jpg", color: "#9c9a96", priority: 80, pole: { ra: 281.0103, dec: 61.4155 }, subtitle: "Planet · Solar System" },
  { id: "venus", name: "Venus", type: "planet", horizons: "299", factsheet: "VENUS", wiki: "Venus", texture: "2k_venus_atmosphere.jpg", color: "#e2c48f", priority: 82, pole: { ra: 272.76, dec: 67.16 }, subtitle: "Planet · Solar System" },
  { id: "earth", name: "Earth", aliases: ["Home", "Terra"], type: "planet", horizons: "399", factsheet: "EARTH", wiki: "Earth", texture: "2k_earth_daymap.jpg", color: "#3d7be0", priority: 100, pole: { ra: 0, dec: 90 }, subtitle: "Planet · Solar System · You are here" },
  { id: "moon", name: "Moon", aliases: ["Luna", "The Moon"], type: "moon", horizons: "301", parent: "earth", factsheet: "MOON", wiki: "Moon", texture: "2k_moon.jpg", color: "#b8b5ae", priority: 90, pole: { ra: 269.9949, dec: 66.5392 }, subtitle: "Moon of Earth" },
  { id: "mars", name: "Mars", aliases: ["Red Planet"], type: "planet", horizons: "499", factsheet: "MARS", wiki: "Mars", texture: "2k_mars.jpg", color: "#c8643c", priority: 95, pole: { ra: 317.681, dec: 52.887 }, subtitle: "Planet · Solar System" },
  { id: "phobos", name: "Phobos", type: "moon", horizons: "401", parent: "mars", wiki: "Phobos_(moon)", color: "#8a7f74", priority: 40, subtitle: "Moon of Mars" },
  { id: "deimos", name: "Deimos", type: "moon", horizons: "402", parent: "mars", wiki: "Deimos_(moon)", color: "#9a8f84", priority: 30, subtitle: "Moon of Mars" },
  { id: "jupiter", name: "Jupiter", type: "planet", horizons: "599", factsheet: "JUPITER", wiki: "Jupiter", texture: "2k_jupiter.jpg", color: "#d2a77a", priority: 92, pole: { ra: 268.056595, dec: 64.495303 }, subtitle: "Gas giant · Solar System" },
  { id: "io", name: "Io", type: "moon", horizons: "501", parent: "jupiter", wiki: "Io_(moon)", color: "#e3cf6a", priority: 50, subtitle: "Galilean moon of Jupiter" },
  { id: "europa", name: "Europa", type: "moon", horizons: "502", parent: "jupiter", wiki: "Europa_(moon)", color: "#cdbfa8", priority: 60, subtitle: "Galilean moon of Jupiter" },
  { id: "ganymede", name: "Ganymede", type: "moon", horizons: "503", parent: "jupiter", wiki: "Ganymede_(moon)", color: "#a69a8c", priority: 50, subtitle: "Galilean moon of Jupiter" },
  { id: "callisto", name: "Callisto", type: "moon", horizons: "504", parent: "jupiter", wiki: "Callisto_(moon)", color: "#7d7366", priority: 45, subtitle: "Galilean moon of Jupiter" },
  { id: "saturn", name: "Saturn", type: "planet", horizons: "699", factsheet: "SATURN", wiki: "Saturn", texture: "2k_saturn.jpg", color: "#e0c690", priority: 94, pole: { ra: 40.589, dec: 83.537 }, rings: { innerKm: 74_658, outerKm: 136_780, texture: "2k_saturn_ring_alpha.png" }, subtitle: "Gas giant · Solar System" },
  { id: "enceladus", name: "Enceladus", type: "moon", horizons: "602", parent: "saturn", wiki: "Enceladus", color: "#eef2f5", priority: 50, subtitle: "Moon of Saturn" },
  { id: "titan", name: "Titan", type: "moon", horizons: "606", parent: "saturn", wiki: "Titan_(moon)", color: "#d9a650", priority: 60, subtitle: "Moon of Saturn" },
  { id: "uranus", name: "Uranus", type: "planet", horizons: "799", factsheet: "URANUS", wiki: "Uranus", texture: "2k_uranus.jpg", color: "#9fd3dc", priority: 85, pole: { ra: 257.311, dec: -15.175 }, subtitle: "Ice giant · Solar System" },
  { id: "neptune", name: "Neptune", type: "planet", horizons: "899", factsheet: "NEPTUNE", wiki: "Neptune", texture: "2k_neptune.jpg", color: "#4f78d6", priority: 85, pole: { ra: 299.36, dec: 43.46 }, subtitle: "Ice giant · Solar System" },
  { id: "triton", name: "Triton", type: "moon", horizons: "801", parent: "neptune", wiki: "Triton_(moon)", color: "#d6c7c0", priority: 40, subtitle: "Moon of Neptune" },
  { id: "pluto", name: "Pluto", type: "dwarf-planet", horizons: "999", factsheet: "PLUTO", wiki: "Pluto", color: "#c9ad8f", priority: 80, pole: { ra: 132.993, dec: -6.163 }, subtitle: "Dwarf planet · Kuiper belt" },
  { id: "charon", name: "Charon", type: "moon", horizons: "901", parent: "pluto", wiki: "Charon_(moon)", color: "#a39d97", priority: 35, subtitle: "Moon of Pluto" },
  { id: "ceres", name: "Ceres", type: "dwarf-planet", horizons: "1;", wiki: "Ceres_(dwarf_planet)", color: "#8f8a85", priority: 60, subtitle: "Dwarf planet · Asteroid belt" },
  { id: "vesta", name: "Vesta", aliases: ["4 Vesta"], type: "asteroid", horizons: "4;", wiki: "4_Vesta", color: "#a8a29a", priority: 40, subtitle: "Asteroid · Asteroid belt" },
  { id: "bennu", name: "Bennu", aliases: ["101955 Bennu"], type: "asteroid", horizons: "101955;", wiki: "101955_Bennu", color: "#6c6863", priority: 35, subtitle: "Near-Earth asteroid · sampled by OSIRIS-REx" },
  { id: "eris", name: "Eris", type: "dwarf-planet", horizons: "136199;", wiki: "Eris_(dwarf_planet)", color: "#dcd8d2", priority: 45, subtitle: "Dwarf planet · Scattered disc" },
  { id: "arrokoth", name: "Arrokoth", aliases: ["486958 Arrokoth", "Ultima Thule"], type: "asteroid", horizons: "486958;", wiki: "486958_Arrokoth", color: "#b07a5a", priority: 35, subtitle: "Kuiper belt object · visited by New Horizons" },
  { id: "halley", name: "Halley's Comet", aliases: ["1P/Halley", "Comet Halley"], type: "comet", horizons: "DES=1P;CAP;NOFRAG", wiki: "Halley's_Comet", color: "#9fc3e6", priority: 55, subtitle: "Periodic comet · returns 2061" },
  { id: "voyager-1", name: "Voyager 1", type: "spacecraft", horizons: "-31", wiki: "Voyager_1", color: "#f2c94c", priority: 75, subtitle: "Spacecraft · Interstellar space" },
  { id: "voyager-2", name: "Voyager 2", type: "spacecraft", horizons: "-32", wiki: "Voyager_2", color: "#f2c94c", priority: 55, subtitle: "Spacecraft · Interstellar space" },
  { id: "new-horizons", name: "New Horizons", type: "spacecraft", horizons: "-98", wiki: "New_Horizons", color: "#f2c94c", priority: 60, subtitle: "Spacecraft · Kuiper belt" },
  { id: "jwst", name: "James Webb Space Telescope", aliases: ["JWST", "Webb"], type: "spacecraft", horizons: "-170", wiki: "James_Webb_Space_Telescope", color: "#f2c94c", priority: 60, subtitle: "Space telescope · near Sun–Earth L2" },
  { id: "europa-clipper", name: "Europa Clipper", type: "spacecraft", horizons: "-159", wiki: "Europa_Clipper", color: "#f2c94c", priority: 45, subtitle: "Spacecraft · en route to Jupiter" },
];

/** Spacecraft whose Horizons heliocentric speed becomes a transport preset. */
export const SPEED_PRESETS = [
  { id: "voyager-1", label: "Voyager 1", horizons: "-31" },
  { id: "new-horizons", label: "New Horizons", horizons: "-98" },
];
/** Parker Solar Probe record perihelion (2024-12-24); speed derived from Horizons vectors. */
export const PARKER = { horizons: "-96", start: "2024-12-24 08:00", stop: "2024-12-24 16:00", step: "1 m" };

export type DistanceSpec =
  | { kind: "parallax" }
  | { kind: "simbad"; bibcode: string }
  | { kind: "literature"; valuePc: number; plusPc?: number; minusPc?: number; bibcode: string; citation: string; quality: "precise" | "good" | "approximate" | "uncertain"; note?: string };

export interface CuratedObject {
  id: string;
  name: string;
  aliases?: string[];
  simbad: string;
  type: "star" | "star-cluster" | "nebula" | "galaxy" | "black-hole" | "quasar";
  region: "stellar-neighborhood" | "milky-way" | "local-group" | "local-volume" | "cosmological";
  wiki: string;
  distance: DistanceSpec | { kind: "none"; reason: string };
  priority: number;
  subtitle?: string;
  exoplanetHost?: string;
  /** Wikimedia Commons file to use instead of the article lead image, or null for none. */
  image?: string | null;
  imageKind?: "observed" | "illustration";
}

export const CURATED: CuratedObject[] = [
  // Stellar neighbourhood
  { id: "proxima-centauri", name: "Proxima Centauri", aliases: ["Proxima", "Alpha Centauri C"], simbad: "NAME Proxima Centauri", type: "star", region: "stellar-neighborhood", wiki: "Proxima_Centauri", distance: { kind: "parallax" }, priority: 95, exoplanetHost: "Proxima Cen" },
  { id: "alpha-centauri-a", name: "Alpha Centauri A", aliases: ["Alpha Centauri", "Rigil Kentaurus", "α Cen A"], simbad: "* alf Cen A", type: "star", region: "stellar-neighborhood", wiki: "Alpha_Centauri", distance: { kind: "parallax" }, priority: 90 },
  { id: "alpha-centauri-b", name: "Alpha Centauri B", aliases: ["Toliman", "α Cen B"], simbad: "* alf Cen B", type: "star", region: "stellar-neighborhood", wiki: "Alpha_Centauri", distance: { kind: "parallax" }, priority: 60, image: null },
  { id: "barnards-star", name: "Barnard's Star", aliases: ["Barnard Star"], simbad: "NAME Barnard's star", type: "star", region: "stellar-neighborhood", wiki: "Barnard's_Star", distance: { kind: "parallax" }, priority: 70, exoplanetHost: "Barnard's star" },
  { id: "wolf-359", name: "Wolf 359", simbad: "Wolf 359", type: "star", region: "stellar-neighborhood", wiki: "Wolf_359", distance: { kind: "parallax" }, priority: 50 },
  { id: "sirius", name: "Sirius", aliases: ["Dog Star", "Alpha Canis Majoris"], simbad: "* alf CMa", type: "star", region: "stellar-neighborhood", wiki: "Sirius", distance: { kind: "parallax" }, priority: 92 },
  { id: "luytens-star", name: "Luyten's Star", aliases: ["GJ 273"], simbad: "GJ 273", type: "star", region: "stellar-neighborhood", wiki: "Luyten's_Star", distance: { kind: "parallax" }, priority: 35, exoplanetHost: "GJ 273" },
  { id: "epsilon-eridani", name: "Epsilon Eridani", aliases: ["Ran", "ε Eri"], simbad: "* eps Eri", type: "star", region: "stellar-neighborhood", wiki: "Epsilon_Eridani", distance: { kind: "parallax" }, priority: 65, exoplanetHost: "eps Eri" },
  { id: "61-cygni", name: "61 Cygni A", aliases: ["61 Cyg A", "Bessel's Star"], simbad: "* 61 Cyg A", type: "star", region: "stellar-neighborhood", wiki: "61_Cygni", distance: { kind: "parallax" }, priority: 45 },
  { id: "procyon", name: "Procyon", aliases: ["Alpha Canis Minoris"], simbad: "* alf CMi", type: "star", region: "stellar-neighborhood", wiki: "Procyon", distance: { kind: "parallax" }, priority: 70 },
  { id: "ross-128", name: "Ross 128", simbad: "Ross 128", type: "star", region: "stellar-neighborhood", wiki: "Ross_128", distance: { kind: "parallax" }, priority: 40, exoplanetHost: "Ross 128" },
  { id: "tau-ceti", name: "Tau Ceti", aliases: ["τ Cet"], simbad: "* tau Cet", type: "star", region: "stellar-neighborhood", wiki: "Tau_Ceti", distance: { kind: "parallax" }, priority: 65, exoplanetHost: "tau Cet" },
  { id: "teegardens-star", name: "Teegarden's Star", simbad: "NAME Teegarden's Star", type: "star", region: "stellar-neighborhood", wiki: "Teegarden's_Star", distance: { kind: "parallax" }, priority: 45, exoplanetHost: "Teegarden's Star" },
  { id: "gliese-581", name: "Gliese 581", aliases: ["GJ 581"], simbad: "GJ 581", type: "star", region: "stellar-neighborhood", wiki: "Gliese_581", distance: { kind: "parallax" }, priority: 45, exoplanetHost: "GJ 581" },
  { id: "altair", name: "Altair", aliases: ["Alpha Aquilae"], simbad: "* alf Aql", type: "star", region: "stellar-neighborhood", wiki: "Altair", distance: { kind: "parallax" }, priority: 70 },
  { id: "vega", name: "Vega", aliases: ["Alpha Lyrae"], simbad: "* alf Lyr", type: "star", region: "stellar-neighborhood", wiki: "Vega", distance: { kind: "parallax" }, priority: 85 },
  { id: "fomalhaut", name: "Fomalhaut", aliases: ["Alpha Piscis Austrini"], simbad: "* alf PsA", type: "star", region: "stellar-neighborhood", wiki: "Fomalhaut", distance: { kind: "parallax" }, priority: 60 },
  { id: "trappist-1", name: "TRAPPIST-1", simbad: "TRAPPIST-1", type: "star", region: "stellar-neighborhood", wiki: "TRAPPIST-1", distance: { kind: "parallax" }, priority: 88, exoplanetHost: "TRAPPIST-1", imageKind: "illustration" },
  { id: "pollux", name: "Pollux", aliases: ["Beta Geminorum"], simbad: "* bet Gem", type: "star", region: "stellar-neighborhood", wiki: "Pollux_(star)", distance: { kind: "parallax" }, priority: 55 },
  { id: "arcturus", name: "Arcturus", aliases: ["Alpha Boötis", "Alpha Bootis"], simbad: "* alf Boo", type: "star", region: "stellar-neighborhood", wiki: "Arcturus", distance: { kind: "parallax" }, priority: 80 },
  { id: "capella", name: "Capella", aliases: ["Alpha Aurigae"], simbad: "* alf Aur", type: "star", region: "stellar-neighborhood", wiki: "Capella", distance: { kind: "parallax" }, priority: 65 },
  { id: "castor", name: "Castor", aliases: ["Alpha Geminorum"], simbad: "* alf Gem", type: "star", region: "stellar-neighborhood", wiki: "Castor_(star)", distance: { kind: "parallax" }, priority: 50 },
  { id: "51-pegasi", name: "51 Pegasi", aliases: ["Helvetios", "51 Peg"], simbad: "* 51 Peg", type: "star", region: "stellar-neighborhood", wiki: "51_Pegasi", distance: { kind: "parallax" }, priority: 55, exoplanetHost: "51 Peg" },
  { id: "lhs-1140", name: "LHS 1140", simbad: "LHS 1140", type: "star", region: "stellar-neighborhood", wiki: "LHS_1140", distance: { kind: "parallax" }, priority: 35, exoplanetHost: "LHS 1140" },
  { id: "hd-189733", name: "HD 189733", simbad: "HD 189733", type: "star", region: "stellar-neighborhood", wiki: "HD_189733", distance: { kind: "parallax" }, priority: 35, exoplanetHost: "HD 189733" },
  { id: "aldebaran", name: "Aldebaran", aliases: ["Alpha Tauri"], simbad: "* alf Tau", type: "star", region: "stellar-neighborhood", wiki: "Aldebaran", distance: { kind: "parallax" }, priority: 70 },
  { id: "regulus", name: "Regulus", aliases: ["Alpha Leonis"], simbad: "* alf Leo", type: "star", region: "stellar-neighborhood", wiki: "Regulus", distance: { kind: "parallax" }, priority: 55 },
  { id: "mizar", name: "Mizar", aliases: ["Zeta Ursae Majoris"], simbad: "* zet UMa", type: "star", region: "stellar-neighborhood", wiki: "Mizar", distance: { kind: "parallax" }, priority: 45 },
  { id: "algol", name: "Algol", aliases: ["Beta Persei", "Demon Star"], simbad: "* bet Per", type: "star", region: "stellar-neighborhood", wiki: "Algol", distance: { kind: "parallax" }, priority: 50 },
  { id: "dubhe", name: "Dubhe", aliases: ["Alpha Ursae Majoris"], simbad: "* alf UMa", type: "star", region: "stellar-neighborhood", wiki: "Dubhe", distance: { kind: "parallax" }, priority: 45 },
  { id: "k2-18", name: "K2-18", simbad: "K2-18", type: "star", region: "stellar-neighborhood", wiki: "K2-18", distance: { kind: "parallax" }, priority: 40, exoplanetHost: "K2-18" },
  { id: "achernar", name: "Achernar", aliases: ["Alpha Eridani"], simbad: "* alf Eri", type: "star", region: "stellar-neighborhood", wiki: "Achernar", distance: { kind: "parallax" }, priority: 50 },
  { id: "hd-209458", name: "HD 209458", aliases: ["Osiris host"], simbad: "HD 209458", type: "star", region: "stellar-neighborhood", wiki: "HD_209458", distance: { kind: "parallax" }, priority: 35, exoplanetHost: "HD 209458" },
  { id: "spica", name: "Spica", aliases: ["Alpha Virginis"], simbad: "* alf Vir", type: "star", region: "stellar-neighborhood", wiki: "Spica", distance: { kind: "parallax" }, priority: 60 },
  { id: "bellatrix", name: "Bellatrix", aliases: ["Gamma Orionis"], simbad: "* gam Ori", type: "star", region: "stellar-neighborhood", wiki: "Bellatrix", distance: { kind: "parallax" }, priority: 45 },
  { id: "thuban", name: "Thuban", aliases: ["Alpha Draconis"], simbad: "* alf Dra", type: "star", region: "stellar-neighborhood", wiki: "Thuban", distance: { kind: "parallax" }, priority: 45 },
  { id: "mira", name: "Mira", aliases: ["Omicron Ceti"], simbad: "* omi Cet", type: "star", region: "stellar-neighborhood", wiki: "Mira", distance: { kind: "parallax" }, priority: 50 },
  { id: "canopus", name: "Canopus", aliases: ["Alpha Carinae"], simbad: "* alf Car", type: "star", region: "stellar-neighborhood", wiki: "Canopus", distance: { kind: "parallax" }, priority: 70 },
  { id: "polaris", name: "Polaris", aliases: ["North Star", "Pole Star", "Alpha Ursae Minoris"], simbad: "* alf UMi", type: "star", region: "stellar-neighborhood", wiki: "Polaris", distance: { kind: "parallax" }, priority: 98, image: null },
  { id: "betelgeuse", name: "Betelgeuse", aliases: ["Alpha Orionis"], simbad: "* alf Ori", type: "star", region: "stellar-neighborhood", wiki: "Betelgeuse", distance: { kind: "parallax" }, priority: 90 },
  { id: "antares", name: "Antares", aliases: ["Alpha Scorpii"], simbad: "* alf Sco", type: "star", region: "stellar-neighborhood", wiki: "Antares", distance: { kind: "parallax" }, priority: 70 },
  { id: "kepler-186", name: "Kepler-186", simbad: "Kepler-186", type: "star", region: "milky-way", wiki: "Kepler-186", distance: { kind: "parallax" }, priority: 45, exoplanetHost: "Kepler-186" },
  { id: "kepler-22", name: "Kepler-22", simbad: "Kepler-22", type: "star", region: "milky-way", wiki: "Kepler-22", distance: { kind: "parallax" }, priority: 40, exoplanetHost: "Kepler-22" },
  { id: "rigel", name: "Rigel", aliases: ["Beta Orionis"], simbad: "* bet Ori", type: "star", region: "milky-way", wiki: "Rigel", distance: { kind: "parallax" }, priority: 80 },
  { id: "tabbys-star", name: "Tabby's Star", aliases: ["Boyajian's Star", "KIC 8462852"], simbad: "KIC 8462852", type: "star", region: "milky-way", wiki: "Tabby's_Star", distance: { kind: "parallax" }, priority: 40 },
  { id: "kepler-452", name: "Kepler-452", simbad: "Kepler-452", type: "star", region: "milky-way", wiki: "Kepler-452", distance: { kind: "parallax" }, priority: 45, exoplanetHost: "Kepler-452" },
  { id: "alnilam", name: "Alnilam", aliases: ["Epsilon Orionis", "Orion's Belt"], simbad: "* eps Ori", type: "star", region: "milky-way", wiki: "Alnilam", distance: { kind: "parallax" }, priority: 45 },
  {
    id: "deneb", name: "Deneb", aliases: ["Alpha Cygni"], simbad: "* alf Cyg", type: "star", region: "milky-way", wiki: "Deneb", priority: 80,
    distance: { kind: "literature", valuePc: 802, plusPc: 66, minusPc: 66, bibcode: "2008A&A...479..849S", citation: "Schiller & Przybilla 2008, A&A 479, 849", quality: "uncertain", note: "The Hipparcos parallax (2.31 ± 0.32 mas) implies only ~430 pc; spectroscopic modelling gives ~800 pc. Deneb's distance is genuinely uncertain." },
  },
  {
    id: "vy-canis-majoris", name: "VY Canis Majoris", aliases: ["VY CMa"], simbad: "V* VY CMa", type: "star", region: "milky-way", wiki: "VY_Canis_Majoris", priority: 50,
    distance: { kind: "literature", valuePc: 1170, plusPc: 110, minusPc: 90, bibcode: "2012ApJ...744...23Z", citation: "Zhang et al. 2012, ApJ 744, 23 (maser parallax)", quality: "approximate", note: "Gaia's parallax for this star is not usable (error ≈ 97%); we use a radio maser parallax instead." },
  },
  {
    id: "eta-carinae", name: "Eta Carinae", aliases: ["η Car"], simbad: "* eta Car", type: "star", region: "milky-way", wiki: "Eta_Carinae", priority: 55,
    distance: { kind: "literature", valuePc: 2350, plusPc: 50, minusPc: 50, bibcode: "2006ApJ...644.1151S", citation: "Smith 2006, ApJ 644, 1151", quality: "good" },
  },
  // Milky Way deep sky
  { id: "hyades", name: "Hyades", aliases: ["Melotte 25"], simbad: "Cl Melotte 25", type: "star-cluster", region: "stellar-neighborhood", wiki: "Hyades_(star_cluster)", distance: { kind: "parallax" }, priority: 50, subtitle: "Open star cluster · Taurus" },
  { id: "pleiades", name: "Pleiades", aliases: ["Seven Sisters", "M45", "Subaru"], simbad: "M 45", type: "star-cluster", region: "stellar-neighborhood", wiki: "Pleiades", distance: { kind: "parallax" }, priority: 85, subtitle: "Open star cluster · Taurus" },
  { id: "helix-nebula", name: "Helix Nebula", aliases: ["NGC 7293", "Eye of God"], simbad: "NGC 7293", type: "nebula", region: "milky-way", wiki: "Helix_Nebula", distance: { kind: "parallax" }, priority: 50, subtitle: "Planetary nebula · Aquarius" },
  {
    id: "orion-nebula", name: "Orion Nebula", aliases: ["M42", "Messier 42"], simbad: "M 42", type: "nebula", region: "milky-way", wiki: "Orion_Nebula", priority: 88, subtitle: "Star-forming nebula · Orion",
    distance: { kind: "literature", valuePc: 414, plusPc: 7, minusPc: 7, bibcode: "2007A&A...474..515M", citation: "Menten et al. 2007, A&A 474, 515 (VLBA parallax)", quality: "good" },
  },
  { id: "ring-nebula", name: "Ring Nebula", aliases: ["M57", "Messier 57"], simbad: "M 57", type: "nebula", region: "milky-way", wiki: "Ring_Nebula", distance: { kind: "parallax" }, priority: 55, subtitle: "Planetary nebula · Lyra" },
  { id: "eagle-nebula", name: "Eagle Nebula", aliases: ["M16", "Pillars of Creation"], simbad: "M 16", type: "nebula", region: "milky-way", wiki: "Eagle_Nebula", distance: { kind: "parallax" }, priority: 70, subtitle: "Star-forming region · Serpens" },
  { id: "crab-nebula", name: "Crab Nebula", aliases: ["M1", "Messier 1"], simbad: "M 1", type: "nebula", region: "milky-way", wiki: "Crab_Nebula", distance: { kind: "simbad", bibcode: "1973PASP...85..579T" }, priority: 70, subtitle: "Supernova remnant · Taurus" },
  { id: "47-tucanae", name: "47 Tucanae", aliases: ["NGC 104", "47 Tuc"], simbad: "NGC 104", type: "star-cluster", region: "milky-way", wiki: "47_Tucanae", distance: { kind: "parallax" }, priority: 45, subtitle: "Globular cluster · Tucana" },
  { id: "omega-centauri", name: "Omega Centauri", aliases: ["NGC 5139", "ω Cen"], simbad: "NGC 5139", type: "star-cluster", region: "milky-way", wiki: "Omega_Centauri", distance: { kind: "parallax" }, priority: 60, subtitle: "Globular cluster · Centaurus" },
  { id: "m13", name: "Hercules Cluster", aliases: ["M13", "Messier 13", "Great Globular Cluster"], simbad: "M 13", type: "star-cluster", region: "milky-way", wiki: "Messier_13", distance: { kind: "parallax" }, priority: 50, subtitle: "Globular cluster · Hercules" },
  {
    id: "sagittarius-a-star", name: "Sagittarius A*", aliases: ["Sgr A*", "Galactic Center", "Milky Way black hole", "Center of the Milky Way"], simbad: "NAME Sgr A*", type: "black-hole", region: "milky-way", wiki: "Sagittarius_A*", priority: 90, subtitle: "Supermassive black hole · Galactic Center",
    distance: { kind: "literature", valuePc: 8178, plusPc: 25, minusPc: 25, bibcode: "2019A&A...625L..10G", citation: "GRAVITY Collaboration 2019, A&A 625, L10 (8178 ± 13 stat ± 22 sys pc)", quality: "precise" },
  },
  // Local Group
  {
    id: "lmc", name: "Large Magellanic Cloud", aliases: ["LMC"], simbad: "NAME LMC", type: "galaxy", region: "local-group", wiki: "Large_Magellanic_Cloud", priority: 80, subtitle: "Satellite galaxy of the Milky Way",
    distance: { kind: "literature", valuePc: 49_590, plusPc: 550, minusPc: 550, bibcode: "2019Natur.567..200P", citation: "Pietrzyński et al. 2019, Nature 567, 200 (49.59 ± 0.09 stat ± 0.54 sys kpc)", quality: "precise" },
  },
  {
    id: "smc", name: "Small Magellanic Cloud", aliases: ["SMC"], simbad: "NAME SMC", type: "galaxy", region: "local-group", wiki: "Small_Magellanic_Cloud", priority: 65, subtitle: "Satellite galaxy of the Milky Way",
    distance: { kind: "literature", valuePc: 62_440, plusPc: 940, minusPc: 940, bibcode: "2020ApJ...904...13G", citation: "Graczyk et al. 2020, ApJ 904, 13 (62.44 ± 0.47 stat ± 0.81 sys kpc)", quality: "good" },
  },
  { id: "andromeda", name: "Andromeda Galaxy", aliases: ["M31", "Messier 31", "Andromeda"], simbad: "M 31", type: "galaxy", region: "local-group", wiki: "Andromeda_Galaxy", distance: { kind: "simbad", bibcode: "2021ApJ...920...84L" }, priority: 95, subtitle: "Spiral galaxy · Local Group" },
  { id: "triangulum", name: "Triangulum Galaxy", aliases: ["M33", "Messier 33"], simbad: "M 33", type: "galaxy", region: "local-group", wiki: "Triangulum_Galaxy", distance: { kind: "simbad", bibcode: "2023ApJ...951..118B" }, priority: 70, subtitle: "Spiral galaxy · Local Group" },
  // Local Volume (redshift-independent distances, z < 0.005)
  { id: "m81", name: "Bode's Galaxy", aliases: ["M81", "Messier 81"], simbad: "M 81", type: "galaxy", region: "local-volume", wiki: "Messier_81", distance: { kind: "simbad", bibcode: "2013AJ....146...86T" }, priority: 55, subtitle: "Spiral galaxy · M81 Group" },
  { id: "centaurus-a", name: "Centaurus A", aliases: ["NGC 5128", "Cen A"], simbad: "NGC 5128", type: "galaxy", region: "local-volume", wiki: "Centaurus_A", distance: { kind: "simbad", bibcode: "2013AJ....146...86T" }, priority: 55, subtitle: "Radio galaxy · Centaurus A/M83 Group" },
  { id: "m101", name: "Pinwheel Galaxy", aliases: ["M101", "Messier 101"], simbad: "M 101", type: "galaxy", region: "local-volume", wiki: "Pinwheel_Galaxy", distance: { kind: "simbad", bibcode: "2013AJ....146...86T" }, priority: 55, subtitle: "Spiral galaxy · Ursa Major" },
  { id: "whirlpool", name: "Whirlpool Galaxy", aliases: ["M51", "Messier 51"], simbad: "M 51", type: "galaxy", region: "local-volume", wiki: "Whirlpool_Galaxy", distance: { kind: "simbad", bibcode: "2010ApJS..190..233M" }, priority: 60, subtitle: "Interacting spiral galaxy · Canes Venatici" },
  { id: "sombrero", name: "Sombrero Galaxy", aliases: ["M104", "Messier 104"], simbad: "M 104", type: "galaxy", region: "local-volume", wiki: "Sombrero_Galaxy", distance: { kind: "simbad", bibcode: "2013AJ....146...86T" }, priority: 55, subtitle: "Spiral galaxy · Virgo" },
  { id: "m87", name: "Messier 87", aliases: ["M87", "Virgo A", "M87*"], simbad: "M 87", type: "galaxy", region: "local-volume", wiki: "Messier_87", distance: { kind: "simbad", bibcode: "2013AJ....146...86T" }, priority: 70, subtitle: "Giant elliptical galaxy · Virgo Cluster" },
  // Cosmological: searchable, but no Euclidean route
  {
    id: "3c-273", name: "3C 273", aliases: ["Quasar 3C 273"], simbad: "3C 273", type: "quasar", region: "cosmological", wiki: "3C_273", priority: 45, subtitle: "Quasar · redshift z ≈ 0.158",
    distance: { kind: "none", reason: "3C 273 is at cosmological redshift (z ≈ 0.158). Its distance depends on which cosmological definition is used (light-travel, comoving, luminosity), and space expands during any journey, so a constant-speed straight-line route is not meaningful." },
  },
  {
    id: "ton-618", name: "TON 618", simbad: "TON 618", type: "quasar", region: "cosmological", wiki: "TON_618", priority: 40, subtitle: "Quasar · redshift z ≈ 2.2",
    distance: { kind: "none", reason: "TON 618 is at redshift z ≈ 2.2. Light-travel, comoving and luminosity distances differ by factors of several at this redshift, and cosmic expansion makes a fixed-speed route undefined." },
  },
];
